name: fatoora
description: تطبيق الواضح فاتورة يقوم بإصدار الفاتورة الإلكترونية حسب مواصفات هيئة الزكاة والدخل بالسعودية
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  http: ^0.13.4
  http_parser: ^4.0.0
  intl: ^0.17.0
  provider: ^6.0.1
  gsheets: ^0.3.2
  sqflite: ^2.0.1
  sprintf: ^6.0.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  path_provider: ^2.0.1
  open_file: ^3.1.0
  pdf: ^3.6.4
  image_picker: ^0.8.4+4
  image: ^3.1.3
  esc_pos_utils_plus: ^2.0.1+6
  pdf_render: ^1.0.18
  sunmi_printer_plus: ^2.0.13
  sqflite_common_ffi: ^2.2.0+1
  file_picker: ^4.6.1
  dropdown_search: ^5.0.5
  url_launcher: ^6.1.7
  share_plus: ^4.5.3
  whatsapp_share2: ^2.0.2
  pdfx: ^2.3.0
  font_awesome_flutter: ^10.4.0
  number_to_word_arabic: ^0.0.8
  package_info: ^2.0.2
  horizontal_data_table: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/fonts/Cairo-Regular.ttf
   - assets/fonts/Cairo-Bold.ttf
   - assets/fonts/arial.ttf
   - assets/fonts/arialbd.ttf
   - assets/fonts/cour.ttf
   - assets/fonts/courbd.ttf
   - assets/fonts/Tahoma.ttf
   - assets/resources/capabilities.json
  fonts:
   - family: Calibri
     fonts:
       - asset: assets/fonts/calibri.ttf
       - asset: assets/fonts/calibrib.ttf
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf
       - asset: assets/fonts/Cairo-Bold.ttf
   - family: Arial
     fonts:
       - asset: assets/fonts/arial.ttf
       - asset: assets/fonts/arialbd.ttf

   - family: Courier New
     fonts:
      - asset: assets/fonts/cour.ttf
      - asset: assets/fonts/courbd.ttf
   - family: Tahoma
     fonts:
      - asset: assets/fonts/Tahoma.ttf
